import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

export interface Pair {
  certPem: string;
  keyPem: string;
  /** notBefore, as openssl set it: the moment of generation. */
  issuedAt: Date;
}

export const DAY_MS = 86_400_000;

/**
 * Real certificates, generated by openssl at test time.
 *
 * Not checked-in fixture strings. A committed certificate expires, and the test
 * that depended on it then fails on a date rather than on a change — the most
 * expensive kind of failure to diagnose, because nothing in the diff explains
 * it.
 *
 * ONLY `-days`. An earlier version used `-not_before`/`-not_after` to place a
 * certificate in the past, which works on OpenSSL 3.5 and fails on everything
 * older — including CI. Nothing here needs backdating: `checkBundle` takes
 * `now` as a parameter, so a test that wants an expired certificate moves the
 * clock forward instead of moving the certificate back. That is both portable
 * and a better test, because it never depends on when it runs.
 */
export function makePair(
  options: {
    subject?: string;
    sans?: string[];
    /** Lifetime from the moment of generation. */
    days?: number;
  } = {},
): Pair {
  const dir = mkdtempSync(join(tmpdir(), 'nexuspuppet-cert-'));
  try {
    const keyPath = join(dir, 'key.pem');
    const certPath = join(dir, 'cert.pem');
    const subject = options.subject ?? '/CN=console.example.test';
    const sans = options.sans ?? ['console.example.test'];
    const days = options.days ?? 365;

    execFileSync(
      'openssl',
      ['genpkey', '-algorithm', 'RSA', '-pkeyopt', 'rsa_keygen_bits:2048', '-out', keyPath],
      { stdio: 'pipe' },
    );

    execFileSync(
      'openssl',
      [
        'req',
        '-new',
        '-x509',
        '-key',
        keyPath,
        '-out',
        certPath,
        '-subj',
        subject,
        '-addext',
        `subjectAltName=${sans.map((s) => `DNS:${s}`).join(',')}`,
        '-days',
        String(days),
      ],
      { stdio: 'pipe' },
    );

    const certPem = readFileSync(certPath, 'utf8');
    return {
      certPem,
      keyPem: readFileSync(keyPath, 'utf8'),
      // Read back rather than assumed: openssl truncates to whole seconds, so
      // Date.now() here can sit a fraction AFTER notBefore and a test using it
      // as "inside the window" would be right by luck.
      issuedAt: new Date(readValidFrom(certPath)),
    };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function readValidFrom(certPath: string): string {
  const out = execFileSync('openssl', ['x509', '-in', certPath, '-noout', '-startdate'], {
    encoding: 'utf8',
  });
  return out.replace(/^notBefore=/, '').trim();
}
