import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

export interface Pair {
  certPem: string;
  keyPem: string;
}

/**
 * Real certificates, generated by openssl at test time.
 *
 * Not checked-in fixture strings. A committed certificate expires, and the test
 * that depended on it then fails on a date rather than on a change — which is
 * the most expensive kind of failure to diagnose, because nothing in the diff
 * explains it. Generating means the validity window is whatever the test asks
 * for.
 */
export function makePair(options: {
  subject?: string;
  sans?: string[];
  /** Relative to now. Negative for an already-expired certificate. */
  daysFrom?: number;
  daysTo?: number;
}): Pair {
  const dir = mkdtempSync(join(tmpdir(), 'nexuspuppet-cert-'));
  try {
    const keyPath = join(dir, 'key.pem');
    const certPath = join(dir, 'cert.pem');
    const subject = options.subject ?? '/CN=console.example.test';
    const sans = options.sans ?? ['console.example.test'];
    // Yesterday, not "now". A certificate whose notBefore is the instant of
    // generation is not-yet-valid against any clock read before it — and RSA
    // keygen takes seconds, so a suite comparing against a `new Date()` from
    // module load drifts into failure part-way through. Real certificates are
    // issued before they are installed; the fixture should behave the same.
    const daysFrom = options.daysFrom ?? -1;
    const daysTo = options.daysTo ?? 365;

    execFileSync(
      'openssl',
      ['genpkey', '-algorithm', 'RSA', '-pkeyopt', 'rsa_keygen_bits:2048', '-out', keyPath],
      {
        stdio: 'pipe',
      },
    );

    const args = [
      'req',
      '-new',
      '-x509',
      '-key',
      keyPath,
      '-out',
      certPath,
      '-subj',
      subject,
      '-addext',
      `subjectAltName=${sans.map((s) => `DNS:${s}`).join(',')}`,
      // -days sets notAfter; -not_before/-not_after give an explicit window,
      // which is what an expiry test needs.
      '-not_before',
      formatAsn1(daysFrom),
      '-not_after',
      formatAsn1(daysTo),
    ];
    execFileSync('openssl', args, { stdio: 'pipe' });

    return {
      certPem: readFileSync(certPath, 'utf8'),
      keyPem: readFileSync(keyPath, 'utf8'),
    };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

/** openssl wants YYYYMMDDHHMMSSZ. */
function formatAsn1(daysFromNow: number): string {
  const at = new Date(Date.now() + daysFromNow * 86_400_000);
  const p = (n: number, w = 2) => String(n).padStart(w, '0');
  return (
    `${at.getUTCFullYear()}${p(at.getUTCMonth() + 1)}${p(at.getUTCDate())}` +
    `${p(at.getUTCHours())}${p(at.getUTCMinutes())}${p(at.getUTCSeconds())}Z`
  );
}
