import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { ldapSettingsSchema } from '@nexuspuppet/contracts';
import { CaPemError, parseCaPem, summariseCaPem } from './ca-pem';
import { ldapConfigSchema } from './config';

/**
 * A CA pasted into the console (ADR-0029 §5), against REAL certificates
 * generated by openssl — the shape an operator's CA actually emits — rather
 * than hand-written blobs that only prove the parser agrees with whoever
 * wrote them.
 */
describe('parseCaPem', () => {
  let dir: string;
  let caCert: string;
  let caKey: string;
  let secondCert: string;

  const generate = (name: string, subject: string): { cert: string; key: string } => {
    const cert = join(dir, `${name}.crt`);
    const key = join(dir, `${name}.key`);
    execFileSync(
      'openssl',
      // openssl's key-generation progress goes to stderr; ignored so it does
      // not bury the test output.
      ['req', '-x509', '-newkey', 'rsa:2048', '-nodes', '-days', '30'].concat([
        '-keyout',
        key,
        '-out',
        cert,
        '-subj',
        subject,
      ]),
      { stdio: 'ignore' },
    );
    return { cert: readFileSync(cert, 'utf8'), key: readFileSync(key, 'utf8') };
  };

  beforeAll(() => {
    dir = mkdtempSync(join(tmpdir(), 'nexuspuppet-ca-pem-'));
    const ca = generate('ca', '/CN=Corp Root CA/O=Corp');
    caCert = ca.cert;
    caKey = ca.key;
    secondCert = generate('intermediate', '/CN=Corp Issuing CA').cert;
  });

  afterAll(() => rmSync(dir, { recursive: true, force: true }));

  it('accepts a CA certificate and reports who it is, so the operator can check the paste', () => {
    const [summary, ...rest] = parseCaPem(caCert);

    expect(rest).toHaveLength(0);
    expect(summary?.subject).toContain('CN=Corp Root CA');
    expect(summary?.issuer).toContain('CN=Corp Root CA');
    expect(summary?.expired).toBe(false);
    expect(Date.parse(summary?.validTo ?? '')).toBeGreaterThan(Date.now());
  });

  it('accepts a bundle, one summary per certificate, in order', () => {
    const summaries = parseCaPem(`${caCert}\n${secondCert}`);

    expect(summaries.map((s) => s.subject)).toEqual([
      expect.stringContaining('Corp Root CA'),
      expect.stringContaining('Corp Issuing CA'),
    ]);
  });

  it('tolerates the subject= lines openssl prints above a certificate', () => {
    const decorated = `subject=CN = Corp Root CA\nissuer=CN = Corp Root CA\n${caCert}`;

    expect(parseCaPem(decorated)).toHaveLength(1);
  });

  it('REFUSES a private key, and says so by name', () => {
    expect(() => parseCaPem(caKey)).toThrow(CaPemError);
    expect(() => parseCaPem(caKey)).toThrow(/PRIVATE KEY/);
  });

  it('refuses a certificate with its private key pasted alongside it', () => {
    // The common way this happens: a combined .pem from a server, not a CA.
    expect(() => parseCaPem(`${caCert}\n${caKey}`)).toThrow(/PRIVATE KEY/);
  });

  it('refuses garbage with a message about the shape it expected', () => {
    expect(() => parseCaPem('not a certificate at all')).toThrow(/BEGIN CERTIFICATE/);
  });

  it('refuses a block that is not a certificate, naming its type', () => {
    const publicKey = '-----BEGIN PUBLIC KEY-----\nMFkw\n-----END PUBLIC KEY-----';
    expect(() => parseCaPem(publicKey)).toThrow(/"PUBLIC KEY" block/);
  });

  it('refuses a certificate that has been truncated in the copy', () => {
    const lines = caCert.trim().split('\n');
    const truncated = [...lines.slice(0, 4), lines[lines.length - 1]].join('\n');

    expect(() => parseCaPem(truncated)).toThrow(/does not parse/);
  });

  it('summarises a stored value without ever throwing', () => {
    expect(summariseCaPem(undefined)).toEqual([]);
    expect(summariseCaPem('garbage')).toEqual([]);
    expect(summariseCaPem(caCert)).toHaveLength(1);
  });

  describe('through the schemas a configuration actually passes', () => {
    const base = { url: 'ldaps://dc.example.test:636', searchBase: 'dc=example,dc=test' };

    it('the settings contract refuses a private key before the API sees it', () => {
      const parsed = ldapSettingsSchema.safeParse({ ...base, caPem: caKey });

      expect(parsed.success).toBe(false);
      expect(JSON.stringify(parsed.error?.issues)).toContain('private key');
    });

    it('the provider schema refuses a certificate that does not parse', () => {
      const broken = caCert.replace(/[A-Za-z0-9+/]{10}\n/, '!!!!!!!!!!\n');
      const parsed = ldapConfigSchema.safeParse({ ...base, caPem: broken });

      expect(parsed.success).toBe(false);
    });

    it('the provider schema accepts a good one unchanged', () => {
      const parsed = ldapConfigSchema.safeParse({ ...base, caPem: caCert });

      expect(parsed.success).toBe(true);
      expect(parsed.data?.caPem).toBe(caCert);
    });
  });
});
